// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: rce.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpawnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*SpawnRequest_File_
	//	*SpawnRequest_Head_
	//	*SpawnRequest_Stdin_
	//	*SpawnRequest_Start_
	Payload isSpawnRequest_Payload `protobuf_oneof:"payload"`
}

func (x *SpawnRequest) Reset() {
	*x = SpawnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest) ProtoMessage() {}

func (x *SpawnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest.ProtoReflect.Descriptor instead.
func (*SpawnRequest) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{0}
}

func (m *SpawnRequest) GetPayload() isSpawnRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SpawnRequest) GetFile() *SpawnRequest_File {
	if x, ok := x.GetPayload().(*SpawnRequest_File_); ok {
		return x.File
	}
	return nil
}

func (x *SpawnRequest) GetHead() *SpawnRequest_Head {
	if x, ok := x.GetPayload().(*SpawnRequest_Head_); ok {
		return x.Head
	}
	return nil
}

func (x *SpawnRequest) GetStdin() *SpawnRequest_Stdin {
	if x, ok := x.GetPayload().(*SpawnRequest_Stdin_); ok {
		return x.Stdin
	}
	return nil
}

func (x *SpawnRequest) GetStart() *SpawnRequest_Start {
	if x, ok := x.GetPayload().(*SpawnRequest_Start_); ok {
		return x.Start
	}
	return nil
}

type isSpawnRequest_Payload interface {
	isSpawnRequest_Payload()
}

type SpawnRequest_File_ struct {
	File *SpawnRequest_File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type SpawnRequest_Head_ struct {
	Head *SpawnRequest_Head `protobuf:"bytes,2,opt,name=head,proto3,oneof"`
}

type SpawnRequest_Stdin_ struct {
	Stdin *SpawnRequest_Stdin `protobuf:"bytes,3,opt,name=stdin,proto3,oneof"`
}

type SpawnRequest_Start_ struct {
	Start *SpawnRequest_Start `protobuf:"bytes,4,opt,name=start,proto3,oneof"`
}

func (*SpawnRequest_File_) isSpawnRequest_Payload() {}

func (*SpawnRequest_Head_) isSpawnRequest_Payload() {}

func (*SpawnRequest_Stdin_) isSpawnRequest_Payload() {}

func (*SpawnRequest_Start_) isSpawnRequest_Payload() {}

type PID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PID) Reset() {
	*x = PID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{1}
}

func (x *PID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SpawnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*SpawnResponse_Stdout_
	//	*SpawnResponse_Stderr_
	//	*SpawnResponse_Exit_
	//	*SpawnResponse_Pid
	Payload isSpawnResponse_Payload `protobuf_oneof:"payload"`
}

func (x *SpawnResponse) Reset() {
	*x = SpawnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResponse) ProtoMessage() {}

func (x *SpawnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResponse.ProtoReflect.Descriptor instead.
func (*SpawnResponse) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{2}
}

func (m *SpawnResponse) GetPayload() isSpawnResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SpawnResponse) GetStdout() *SpawnResponse_Stdout {
	if x, ok := x.GetPayload().(*SpawnResponse_Stdout_); ok {
		return x.Stdout
	}
	return nil
}

func (x *SpawnResponse) GetStderr() *SpawnResponse_Stderr {
	if x, ok := x.GetPayload().(*SpawnResponse_Stderr_); ok {
		return x.Stderr
	}
	return nil
}

func (x *SpawnResponse) GetExit() *SpawnResponse_Exit {
	if x, ok := x.GetPayload().(*SpawnResponse_Exit_); ok {
		return x.Exit
	}
	return nil
}

func (x *SpawnResponse) GetPid() *PID {
	if x, ok := x.GetPayload().(*SpawnResponse_Pid); ok {
		return x.Pid
	}
	return nil
}

type isSpawnResponse_Payload interface {
	isSpawnResponse_Payload()
}

type SpawnResponse_Stdout_ struct {
	Stdout *SpawnResponse_Stdout `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type SpawnResponse_Stderr_ struct {
	Stderr *SpawnResponse_Stderr `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type SpawnResponse_Exit_ struct {
	Exit *SpawnResponse_Exit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

type SpawnResponse_Pid struct {
	Pid *PID `protobuf:"bytes,4,opt,name=pid,proto3,oneof"`
}

func (*SpawnResponse_Stdout_) isSpawnResponse_Payload() {}

func (*SpawnResponse_Stderr_) isSpawnResponse_Payload() {}

func (*SpawnResponse_Exit_) isSpawnResponse_Payload() {}

func (*SpawnResponse_Pid) isSpawnResponse_Payload() {}

type KillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{3}
}

func (x *KillResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SpawnRequest_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename   string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content    []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Executable bool   `protobuf:"varint,3,opt,name=executable,proto3" json:"executable,omitempty"`
	Truncate   bool   `protobuf:"varint,4,opt,name=truncate,proto3" json:"truncate,omitempty"`
}

func (x *SpawnRequest_File) Reset() {
	*x = SpawnRequest_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnRequest_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest_File) ProtoMessage() {}

func (x *SpawnRequest_File) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest_File.ProtoReflect.Descriptor instead.
func (*SpawnRequest_File) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SpawnRequest_File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SpawnRequest_File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SpawnRequest_File) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *SpawnRequest_File) GetTruncate() bool {
	if x != nil {
		return x.Truncate
	}
	return false
}

type SpawnRequest_Head struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command  string                   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args     []string                 `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Envs     []*SpawnRequest_Head_Env `protobuf:"bytes,3,rep,name=envs,proto3" json:"envs,omitempty"`
	HasStdin bool                     `protobuf:"varint,4,opt,name=has_stdin,json=hasStdin,proto3" json:"has_stdin,omitempty"`
	Path     string                   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *SpawnRequest_Head) Reset() {
	*x = SpawnRequest_Head{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnRequest_Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest_Head) ProtoMessage() {}

func (x *SpawnRequest_Head) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest_Head.ProtoReflect.Descriptor instead.
func (*SpawnRequest_Head) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SpawnRequest_Head) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SpawnRequest_Head) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SpawnRequest_Head) GetEnvs() []*SpawnRequest_Head_Env {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *SpawnRequest_Head) GetHasStdin() bool {
	if x != nil {
		return x.HasStdin
	}
	return false
}

func (x *SpawnRequest_Head) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SpawnRequest_Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpawnRequest_Start) Reset() {
	*x = SpawnRequest_Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnRequest_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest_Start) ProtoMessage() {}

func (x *SpawnRequest_Start) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest_Start.ProtoReflect.Descriptor instead.
func (*SpawnRequest_Start) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{0, 2}
}

type SpawnRequest_Stdin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdin []byte `protobuf:"bytes,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
}

func (x *SpawnRequest_Stdin) Reset() {
	*x = SpawnRequest_Stdin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnRequest_Stdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest_Stdin) ProtoMessage() {}

func (x *SpawnRequest_Stdin) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest_Stdin.ProtoReflect.Descriptor instead.
func (*SpawnRequest_Stdin) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{0, 3}
}

func (x *SpawnRequest_Stdin) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type SpawnRequest_Head_Env struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SpawnRequest_Head_Env) Reset() {
	*x = SpawnRequest_Head_Env{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnRequest_Head_Env) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest_Head_Env) ProtoMessage() {}

func (x *SpawnRequest_Head_Env) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest_Head_Env.ProtoReflect.Descriptor instead.
func (*SpawnRequest_Head_Env) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *SpawnRequest_Head_Env) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SpawnRequest_Head_Env) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SpawnResponse_Stdout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
}

func (x *SpawnResponse_Stdout) Reset() {
	*x = SpawnResponse_Stdout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnResponse_Stdout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResponse_Stdout) ProtoMessage() {}

func (x *SpawnResponse_Stdout) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResponse_Stdout.ProtoReflect.Descriptor instead.
func (*SpawnResponse_Stdout) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SpawnResponse_Stdout) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

type SpawnResponse_Stderr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stderr []byte `protobuf:"bytes,1,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (x *SpawnResponse_Stderr) Reset() {
	*x = SpawnResponse_Stderr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnResponse_Stderr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResponse_Stderr) ProtoMessage() {}

func (x *SpawnResponse_Stderr) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResponse_Stderr.ProtoReflect.Descriptor instead.
func (*SpawnResponse_Stderr) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{2, 1}
}

func (x *SpawnResponse_Stderr) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

type SpawnResponse_Exit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SpawnResponse_Exit) Reset() {
	*x = SpawnResponse_Exit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rce_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnResponse_Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResponse_Exit) ProtoMessage() {}

func (x *SpawnResponse_Exit) ProtoReflect() protoreflect.Message {
	mi := &file_rce_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResponse_Exit.ProtoReflect.Descriptor instead.
func (*SpawnResponse_Exit) Descriptor() ([]byte, []int) {
	return file_rce_proto_rawDescGZIP(), []int{2, 2}
}

func (x *SpawnResponse_Exit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_rce_proto protoreflect.FileDescriptor

var file_rce_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xd9, 0x04, 0x0a, 0x0c, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x34, 0x0a, 0x05,
	0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x64, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x64,
	0x69, 0x6e, 0x12, 0x34, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x70, 0x61,
	0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48,
	0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x1a, 0x78, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61,
	0x74, 0x65, 0x1a, 0xc9, 0x01, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x65, 0x6e, 0x76,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x2e, 0x45, 0x6e, 0x76, 0x52, 0x04, 0x65, 0x6e, 0x76, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x53, 0x74, 0x64, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x1a,
	0x2d, 0x0a, 0x03, 0x45, 0x6e, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x07,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x1a, 0x1d, 0x0a, 0x05, 0x53, 0x74, 0x64, 0x69, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x15, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xc5, 0x02, 0x0a, 0x0d, 0x53, 0x70, 0x61,
	0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74,
	0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74,
	0x64, 0x6f, 0x75, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74,
	0x64, 0x65, 0x72, 0x72, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x12, 0x32,
	0x0a, 0x04, 0x65, 0x78, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x78, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x65, 0x78,
	0x69, 0x74, 0x12, 0x21, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x49, 0x44, 0x48, 0x00,
	0x52, 0x03, 0x70, 0x69, 0x64, 0x1a, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x1a, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x65, 0x72,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x1a, 0x1a, 0x0a, 0x04, 0x45, 0x78, 0x69,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x24, 0x0a, 0x0c, 0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x85, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x3e, 0x0a,
	0x05, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x2f, 0x0a,
	0x04, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x4b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21,
	0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x79,
	0x6f, 0x75, 0x6e, 0x67, 0x2f, 0x72, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rce_proto_rawDescOnce sync.Once
	file_rce_proto_rawDescData = file_rce_proto_rawDesc
)

func file_rce_proto_rawDescGZIP() []byte {
	file_rce_proto_rawDescOnce.Do(func() {
		file_rce_proto_rawDescData = protoimpl.X.CompressGZIP(file_rce_proto_rawDescData)
	})
	return file_rce_proto_rawDescData
}

var file_rce_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rce_proto_goTypes = []interface{}{
	(*SpawnRequest)(nil),          // 0: protocol.SpawnRequest
	(*PID)(nil),                   // 1: protocol.PID
	(*SpawnResponse)(nil),         // 2: protocol.SpawnResponse
	(*KillResponse)(nil),          // 3: protocol.KillResponse
	(*SpawnRequest_File)(nil),     // 4: protocol.SpawnRequest.File
	(*SpawnRequest_Head)(nil),     // 5: protocol.SpawnRequest.Head
	(*SpawnRequest_Start)(nil),    // 6: protocol.SpawnRequest.Start
	(*SpawnRequest_Stdin)(nil),    // 7: protocol.SpawnRequest.Stdin
	(*SpawnRequest_Head_Env)(nil), // 8: protocol.SpawnRequest.Head.Env
	(*SpawnResponse_Stdout)(nil),  // 9: protocol.SpawnResponse.Stdout
	(*SpawnResponse_Stderr)(nil),  // 10: protocol.SpawnResponse.Stderr
	(*SpawnResponse_Exit)(nil),    // 11: protocol.SpawnResponse.Exit
}
var file_rce_proto_depIdxs = []int32{
	4,  // 0: protocol.SpawnRequest.file:type_name -> protocol.SpawnRequest.File
	5,  // 1: protocol.SpawnRequest.head:type_name -> protocol.SpawnRequest.Head
	7,  // 2: protocol.SpawnRequest.stdin:type_name -> protocol.SpawnRequest.Stdin
	6,  // 3: protocol.SpawnRequest.start:type_name -> protocol.SpawnRequest.Start
	9,  // 4: protocol.SpawnResponse.stdout:type_name -> protocol.SpawnResponse.Stdout
	10, // 5: protocol.SpawnResponse.stderr:type_name -> protocol.SpawnResponse.Stderr
	11, // 6: protocol.SpawnResponse.exit:type_name -> protocol.SpawnResponse.Exit
	1,  // 7: protocol.SpawnResponse.pid:type_name -> protocol.PID
	8,  // 8: protocol.SpawnRequest.Head.envs:type_name -> protocol.SpawnRequest.Head.Env
	0,  // 9: protocol.RemoteCodeExecutor.Spawn:input_type -> protocol.SpawnRequest
	1,  // 10: protocol.RemoteCodeExecutor.Kill:input_type -> protocol.PID
	2,  // 11: protocol.RemoteCodeExecutor.Spawn:output_type -> protocol.SpawnResponse
	3,  // 12: protocol.RemoteCodeExecutor.Kill:output_type -> protocol.KillResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rce_proto_init() }
func file_rce_proto_init() {
	if File_rce_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rce_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnRequest_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnRequest_Head); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnRequest_Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnRequest_Stdin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnRequest_Head_Env); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnResponse_Stdout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnResponse_Stderr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rce_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnResponse_Exit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rce_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SpawnRequest_File_)(nil),
		(*SpawnRequest_Head_)(nil),
		(*SpawnRequest_Stdin_)(nil),
		(*SpawnRequest_Start_)(nil),
	}
	file_rce_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SpawnResponse_Stdout_)(nil),
		(*SpawnResponse_Stderr_)(nil),
		(*SpawnResponse_Exit_)(nil),
		(*SpawnResponse_Pid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rce_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rce_proto_goTypes,
		DependencyIndexes: file_rce_proto_depIdxs,
		MessageInfos:      file_rce_proto_msgTypes,
	}.Build()
	File_rce_proto = out.File
	file_rce_proto_rawDesc = nil
	file_rce_proto_goTypes = nil
	file_rce_proto_depIdxs = nil
}
